# Generated by Django 5.1.1 on 2024-09-24 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuketBelumMenikah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jenis_kelamin", models.CharField(max_length=255)),
                ("ttl", models.CharField(max_length=255)),
                ("suku", models.CharField(max_length=255)),
                ("agama", models.CharField(max_length=255)),
                ("nik", models.CharField(max_length=255)),
                ("alamat", models.CharField(max_length=255)),
                (
                    "penulis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
