# Generated by Django 5.1.1 on 2024-09-24 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketbelummenikah",
            name="date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="suketbelummenikah",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
