# Generated by Django 5.1.1 on 2024-09-26 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_suketvaksinnikah"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuketPindahNikah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama1", models.CharField(max_length=255)),
                ("ttl1", models.CharField(max_length=255)),
                ("jenis_kelamin1", models.CharField(max_length=255)),
                ("agama1", models.CharField(max_length=255)),
                ("pekerjaan1", models.CharField(max_length=255)),
                ("alamat1", models.CharField(max_length=255)),
                ("nama2", models.CharField(max_length=255)),
                ("ttl2", models.CharField(max_length=255)),
                ("jenis_kelamin2", models.CharField(max_length=255)),
                ("agama2", models.CharField(max_length=255)),
                ("pekerjaan2", models.CharField(max_length=255)),
                ("alamat2", models.CharField(max_length=255)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("status", models.BooleanField(blank=True, null=True)),
                (
                    "penulis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
