# Generated by Django 5.1.1 on 2024-09-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ktp",
            field=models.URLField(blank=True, null=True),
        ),
    ]
