# Generated by Django 5.1.1 on 2024-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_alter_profile_ktp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nik",
            field=models.CharField(max_length=16),
        ),
    ]
