# Generated by Django 5.1.1 on 2024-10-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_alter_profile_nik"),
    ]

    operations = [
        migrations.CreateModel(
            name="PengaduanAsing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("ktp", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
