# Generated by Django 5.1.1 on 2024-10-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_pengaduanasing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skck",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketahliwaris",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketbelummenikah",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketkehilangan",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketkelahiran",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketkematian",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketktpbedanama",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketmtq",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketpenghasilantidaktetap",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketpindahnikah",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketrekkeltani",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sukettidakmampu",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketusaha",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="suketvaksinnikah",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
