# Generated by Django 5.1.1 on 2024-10-04 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_alter_skck_status_alter_suketahliwaris_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuketPermohonanKTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("nokk", models.CharField(max_length=255)),
                ("nik", models.CharField(max_length=255)),
                ("alamat", models.CharField(max_length=255)),
                ("pengantarrt", models.URLField(blank=True, null=True)),
                ("scankk", models.URLField(blank=True, null=True)),
                ("scanijasahakta", models.URLField(blank=True, null=True)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "Proses Review"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        default="review",
                        max_length=20,
                    ),
                ),
                (
                    "penulis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
