# Generated by Django 5.1.1 on 2024-10-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_suketpermohonanktp"),
    ]

    operations = [
        migrations.AddField(
            model_name="sukettidakmampu",
            name="pengantarrt",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sukettidakmampu",
            name="scankk",
            field=models.URLField(blank=True, null=True),
        ),
    ]
