# Generated by Django 5.1.1 on 2024-10-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_sukettidakmampu_pengantarrt_sukettidakmampu_scankk"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketahliwaris",
            name="scanktpkkahliwaris1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="scanktpkkahliwaris2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="scanktpkkahliwaris3",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="scanktpkkahliwaris4",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="scanktpsaksi1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="scanktpsaksi2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="skkematian",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="aktaceraikematian",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="fotogandeng",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="pengantarrt",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="scankkistri",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="scankksuami",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="scanktpistri",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suketpindahnikah",
            name="scanktpsuami",
            field=models.URLField(blank=True, null=True),
        ),
    ]
