# Generated by Django 5.1.1 on 2024-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_suketahliwaris_scanktpkkahliwaris1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketbelummenikah",
            name="persyaratan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
