# Generated by Django 5.1.1 on 2024-10-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_suketmtq_dusun_suketmtq_keperluan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketkehilangan",
            name="harikehilangan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
