# Generated by Django 5.1.1 on 2024-10-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_suketkehilangan_harikehilangan"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketkelahiran",
            name="persyaratan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
