# Generated by Django 5.1.1 on 2024-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_suketpenghasilantidaktetap_penghasilan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketahliwaris",
            name="ahliwarisalm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="istri",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="jumlahanak",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="suami",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
