# Generated by Django 5.1.1 on 2024-10-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_rename_ahliwarisalm_suketahliwaris_almarhum"),
    ]

    operations = [
        migrations.AddField(
            model_name="suketahliwaris",
            name="bulanmeninggal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="tahunmeninggal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="suketahliwaris",
            name="tanggalmeninggal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
